<?php
$roles = $this->view->roles;
$role = $_SESSION['ROLE'];
?>
<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($role, $this->resourceCodes('create'), $this->moduleCodes('user'))): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row mb-2">
                <div class="col-11">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-plus-square pr-1"></i>
                        Colaborador
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Colaboradores"
                                onclick="openModule('usuarios');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i>
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formCreateUser" id="formCreateUser" onsubmit="hashPass(this);">
                                <div class="row">
                                    <div class="col-md-12" style="border-radius: 5px;">
                                        <h5 class="pt-2"><i class="fas fa-user pr-1"></i> Dados Pessoais</h5>
                                        <hr>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="name">Nome*</label>
                                            <input type="text" class="form-control" name="name" id="name" required
                                                maxlength="100">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="document_1">CPF</label>
                                            <input type="text" class="form-control" name="document_1" id="document_1"
                                                onchange="validateCPF();">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="document_2">CNPJ</label>
                                            <input type="text" class="form-control" name="document_2" id="document_2"
                                                onchange="validateCNPJ();">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="job_role">Cargo*</label>
                                            <input type="text" class="form-control" name="job_role" id="job_role" required
                                                maxlength="50">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="role_uuid">Nível de Acesso*</label>
                                            <select name="role_uuid" id="role_uuid" class="form-control" required>
                                                <option value="">-</option>
                                                <?php foreach ($roles as $role): ?>
                                                    <option value="<?php echo $role['uuid']; ?>">
                                                        <?php echo $role['name']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="phone">Telefone</label>
                                            <input type="text" class="form-control" name="phone" id="phone">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="cellphone">Celular</label>
                                            <input type="text" class="form-control" name="cellphone" id="cellphone">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="whatsapp">WhatsApp</label>
                                            <input type="text" class="form-control" name="whatsapp" id="whatsapp">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="email">Email*</label>
                                            <input type="email" class="form-control" name="email" id="email" required
                                                maxlength="100">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="password">Nova senha*</label>
                                            <input type="password" class="form-control" name="password" required
                                                minlength="8" maxlength="100">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="confirmation">Confirmar senha*</label>
                                            <input type="password" class="form-control" name="confirmation" required
                                                minlength="8" maxlength="100">
                                        </div>
                                    </div>
                                    <div class="col-md-12" style="border-radius: 5px;">
                                        <h5 class="pt-2"><i class="fas fa-map-marker-alt pr-1"></i> Localização</h5>
                                        <hr>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="postal_code">CEP</label>
                                            <input type="text" class="form-control" name="postal_code" id="postal_code">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="address">Endereço</label>
                                            <input type="text" class="form-control" name="address" id="address"
                                                maxlength="100">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="number">Número</label>
                                            <input type="text" class="form-control" name="number" id="number"
                                                maxlength="50">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="complement">Complemento</label>
                                            <input type="text" class="form-control" name="complement" id="complement"
                                                maxlength="50">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="neighborhood">Bairro</label>
                                            <input type="text" class="form-control" name="neighborhood" id="neighborhood"
                                                maxlength="100">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="city">Cidade</label>
                                            <input type="text" class="form-control" name="city" id="city" maxlength="100">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="state">UF</label>
                                            <input type="text" class="form-control" name="state" id="state" maxlength="2">
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="row">
                                            <div class="col-md-8 mt-2 mb-2">
                                                <button type="submit" class="btn btn-success w-100" id="btnSubmit"
                                                    title="Salvar Colaborador">
                                                    <i class="fa fa-save pr-1"></i> Salvar
                                                </button>
                                            </div>
                                            <div class="col-md-4 mt-2 mb-2">
                                                <button type="button" class="btn btn-outline-primary w-100"
                                                    onclick="openModule('usuarios');" title="Voltar para Colaboradores">
                                                    <i class="fas fa-arrow-left pr-1"></i> Voltar
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="<?php echo baseUrl; ?>public/js/md5.min.js"></script>
    <script>
        function hashPass(form) {
            if (form.password.value !== '') {
                form.password.value = md5(form.password.value);
            }

            if (form.confirmation.value !== '') {
                form.confirmation.value = md5(form.confirmation.value);
            }
        }
    </script>
    <script src="<?php echo baseUrl; ?>public/js/api_cep.js"></script>
    <script src="<?php echo baseUrl; ?>public/js/documents_validators.js"></script>
    <script>
        $(document).ready(function () {
            $("#name").focus();
            $("#document_1").mask("999.999.999-99");
            $("#document_2").mask("99.999.999/9999-99");
            $("#phone").mask("(99)9999-9999");
            $("#cellphone").mask("(99)99999-9999");
            $("#whatsapp").mask("(99)99999-9999");
            $("#postal_code").mask("99999-999");

            $('#formCreateUser').validate({
                rules: {
                    name: {
                        remote: {
                            type: "post",
                            url: "<?php echo baseUrl; ?>painel/usuarios/valor-existente",
                        }
                    },
                    email: {
                        remote: {
                            type: "post",
                            url: "<?php echo baseUrl; ?>painel/usuarios/valor-existente",
                        }
                    },
                    cellphone: {
                        remote: {
                            type: "post",
                            url: "<?php echo baseUrl; ?>painel/usuarios/valor-existente",
                        }
                    },
                },
                messages: {
                    name: {
                        remote: "Nome já cadastrado"
                    },
                    email: {
                        remote: "Email já cadastrado"
                    },
                    cellphone: {
                        remote: "Celular já cadastrado"
                    }
                },
                submitHandler: function (form) {
                    let dados = $(form).serialize();
                    $("#baseLoader").show();
                    $("#btnSubmit").attr('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>painel/usuarios/processa-cadastro",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(function (data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $('#formCreateUser').trigger("reset");
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                    }).fail(function () {
                        showInternalErrorAlert();
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                    });

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>