<?php
$data = $this->view->data;
$isAdmin = $_SESSION['ROLE_ADM'] == '1';
$role = $_SESSION['ROLE'];

$canView = $isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('user'));
$canCreate = $isAdmin || $this->acl($role, $this->resourceCodes('create'), $this->moduleCodes('user'));
$canUpdate = $isAdmin || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('user'));
$canDelete = $isAdmin || $this->acl($role, $this->resourceCodes('delete'), $this->moduleCodes('user'));
$canViewAcl = $isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('privileges'));
?>
<?php if ($canView): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row mb-2">
                <div class="col-6">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-user-cog pr-1"></i>
                        Colaboradores
                    </h1>
                </div>
                <div class="col-6">
                    <?php if ($canCreate): ?>
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item">
                                <button type="button" class="btn btn-outline-success w-100" title="Adicionar Colaborador"
                                    onclick="createUser();" style="position: relative; top: 3px">
                                    <i class="fas fa-plus"></i>
                                </button>
                            </li>
                        </ol>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover" id="table_user" style="width: 99.9%;">
                                    <thead>
                                        <tr class="text-center" style="height: 30px;">
                                            <th style="font-size: 14px; ">Nome</th>
                                            <th style="font-size: 14px;">Email</th>
                                            <th style="font-size: 14px;">Celular</th>
                                            <th style="font-size: 14px;">Cargo</th>
                                            <th style="font-size: 14px;">Perfil</th>
                                            <th style="font-size: 14px;">Situação</th>
                                            <th style="display: none;">CPF</th>
                                            <th style="display: none;">CNPJ</th>
                                            <th style="display: none;">Telefone</th>
                                            <th style="display: none;">Whatsapp</th>
                                            <th style="display: none;">CEP</th>
                                            <th style="display: none;">Endereço</th>
                                            <th style="display: none;">Número</th>
                                            <th style="display: none;">Complemento</th>
                                            <th style="display: none;">Bairro</th>
                                            <th style="display: none;">Cidade</th>
                                            <th style="display: none;">UF</th>
                                            <th style="display: none;">Situação</th>
                                            <th style="display: none;">Cadastrado em</th>
                                            <th style="display: none;">Atualizado em</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($data as $entity): ?>
                                            <tr class="text-center" style="cursor: pointer;"
                                                onclick="openDetails('<?php echo $entity['uuid']; ?>');">
                                                <td style="font-size: 15px; ">
                                                    <?php echo $entity['name']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['email']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['cellphone']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['job_role']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['role']; ?>
                                                </td>
                                                <td style="width: 80px;">
                                                    <?php if ($entity['status'] == '1'): ?>
                                                        <i class="fa fa-circle" style="color: green;"></i>
                                                    <?php else: ?>
                                                        <i class="fa fa-circle" style="color: red;"></i>
                                                    <?php endif; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $entity['document_1']; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $entity['document_2']; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $entity['phone']; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $entity['whatsapp']; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $entity['postal_code']; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $entity['address']; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $entity['number']; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $entity['complement']; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $entity['neighborhood']; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $entity['city']; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $entity['state']; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo ($entity['status'] == '1') ? 'Ativo' : 'Inativo'; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $this->formatDateTime($entity['created_at']); ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $this->formatDateTime($entity['updated_at']); ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">
        $(document).ready(function () {
            let buttonCommon = {
                exportOptions: {
                    format: {
                        body: function (data) {
                            return data;
                        }
                    }
                }
            };

            $('#table_user').DataTable({
                "sDom": 'flBtip',
                searching: true,
                buttons: [
                    $.extend(true, {}, buttonCommon, {
                        extend: 'excel',
                        title: 'USUÁRIOS',
                        exportOptions: { columns: [0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19] }
                    })
                ],
                order: [[4, "asc"]],
                columnDefs: [{ orderable: false, targets: [5] }],
                responsive: true,
                info: true,
                processing: true,
                scrollCollapse: true,
                paging: true,
                "pageLength": 25,
                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ &nbsp;",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Filtrar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });

        function openDetails(uuid) {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>painel/usuarios/detalhes",
                data: { uuid: uuid },
                async: true
            }).done(function (data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function () {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }

    </script>
    <?php if ($canCreate): ?>
        <script>
            function createUser() {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>painel/usuarios/cadastrar",
                    async: true
                }).done(function (data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canUpdate): ?>
        <script>
            function updateUser(uuid) {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>painel/usuarios/editar",
                    data: { uuid: uuid },
                    async: true
                }).done(function (data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canDelete): ?>
        <script>
            function deleteUser(uuid) {
                $("#modalXL").modal('hide');
                $("#modalDeleteTitle").html('<i class="fa fa-trash pr-2"></i> Remover Usuário');
                $("#modalDeleteLoader").hide();
                $("#modalDelete").modal('show');
                $("#modalDeleteResult").html('<button type="button" class="btn btn-danger" title="Confirmar remoção" onclick="runDelete(\'' + uuid + '\');"><i class="fa fa-trash"></i> CONFIRMAR E EXCLUIR</button>');
            }

            function runDelete(uuid) {
                if (uuid !== null) {
                    $("#modalDeleteLoader").show();

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>painel/usuarios/excluir",
                        data: { uuid: uuid },
                        dataType: 'json',
                        async: true
                    }).done(function (data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#modalDelete").modal('hide');
                        $("#modalXL").modal('hide');
                        openModule('usuarios');
                    }).fail(function () {
                        showInternalErrorAlert();
                        $("#modalDeleteLoader").hide();
                    });
                }
            }
        </script>
    <?php endif; ?>
    <?php if ($canViewAcl): ?>
        <script>
            function aclUser(uuid) {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>painel/usuarios/acl",
                    data: { uuid: uuid },
                    async: true
                }).done(function (data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
<?php endif; ?>