<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('customers'))): ?>
    <?php $entity = $this->view->entity; ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row mb-2">
                <div class="col-11">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-info-circle pr-1"></i>
                        Cliente
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Clientes"
                                onclick="openModule('clientes');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i>
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body"> 
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="name">Nome:</label>
                                        <p><?php echo $entity['name']; ?></p>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="name">Email:</label>
                                        <p><?php echo $entity['email']; ?></p>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="name">Telefone:</label>
                                        <p><?php echo $entity['phone'] ? $entity['phone'] : 'Não informado'; ?></p>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="name">Celular:</label>
                                        <p><?php echo $entity['cellphone'] ? $entity['cellphone'] : 'Não informado'; ?></p>
                                    </div>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        <label for="name">CEP:</label>
                                        <p><?php echo $entity['postal_code'] ? $entity['postal_code'] : 'Não informado'; ?></p>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        <label for="name">Endereço:</label>
                                        <p><?php echo $entity['address'] ? $entity['address'] : 'Não informado'; ?></p>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        <label for="name">Número:</label>
                                        <p><?php echo $entity['number'] ? $entity['number'] : 'Não informado'; ?></p>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        <label for="name">Complemento:</label>
                                        <p><?php echo $entity['complement'] ? $entity['complement'] : 'Não informado'; ?></p>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        <label for="name">Bairro:</label>
                                        <p><?php echo $entity['neighborhood'] ? $entity['neighborhood'] : 'Não informado'; ?></p>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        <label for="name">Cidade:</label>
                                        <p><?php echo $entity['city'] ? $entity['city'] : 'Não informada'; ?></p>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        <label for="name">UF:</label>
                                        <p><?php echo $entity['state'] ? $entity['state'] : 'Não informado'; ?></p>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        <label for="name">Situação</label>
                                        <p><?php echo ($entity['status'] == '1') ? 'Ativo' : 'Inativo'; ?></p>
                                    </div>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-6 text-left">
                                    <span>Cadastrado em:</span> <br>
                                    <b>
                                        <?php echo $this->formatDateTime($entity['created_at']); ?>
                                    </b>
                                </div>
                                <div class="col-6 text-right">
                                    <?php if (!empty($entity['updated_at'])): ?>
                                        <span>Atualizado em:</span> <br>
                                        <b>
                                            <?php echo $this->formatDateTime($entity['updated_at']); ?>
                                        </b>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-12">
                                    <hr>
                                </div>
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-4 mt-2 mb-2">
                                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('delete'), $this->moduleCodes('customers'))): ?>
                                                <button type="button" class="btn btn-outline-danger"
                                                    onclick="deleteCustomer('<?php echo $entity['uuid']; ?>');"
                                                    style="width: 100%;" title="Remover Cliente">
                                                    <i class="fa fa-trash"></i> Remover
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                        <div class="col-md-4 mt-2 mb-2">
                                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('update'), $this->moduleCodes('customers'))): ?>
                                                <button type="button" class="btn btn-outline-success"
                                                    onclick="updateCustomer('<?php echo $entity['uuid']; ?>');"
                                                    style="width: 100%;" title="Editar Cliente">
                                                    <i class="fa fa-pen pr-1"></i> Editar
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                        <div class="col-md-4 mt-2 mb-2">
                                            <button type="button" class="btn btn-outline-primary"
                                                onclick="openModule('clientes');" style="width: 100%;"
                                                title="Voltar para Clientes">
                                                <i class="fas fa-arrow-left pr-1"></i> Voltar
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>