<?php $entity = $this->view->entity; ?>
<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('update'), $this->moduleCodes('subcategories'))): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row mb-2">
                <div class="col-11">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-pen-square pr-1"></i>
                        Subcategoria
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Subcategorias"
                                onclick="listSubcategories('<?php echo $_POST['category_uuid']; ?>');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i>
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formUpdateSubcategory" id="formUpdateSubcategory">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="name">Nome</label>
                                            <input type="text" class="form-control" name="name" id="name" required
                                                value="<?php echo $entity['name']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="status">Situação</label>
                                            <select name="status" id="status_1" class="form-control">
                                                <option value="1" <?php echo ($entity['status'] == '1' ? 'selected' : ''); ?>>
                                                    Subcategoria ativa</option>
                                                <option value="0" <?php echo ($entity['status'] == '0' ? 'selected' : ''); ?>>
                                                    Subcategoria inativa</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="row">
                                            <div class="col-md-8 mt-2 mb-2">
                                                <input type="hidden" name="category_uuid"
                                                    value="<?php echo $entity['category_uuid']; ?>">
                                                <input type="hidden" name="uuid" value="<?php echo $entity['uuid']; ?>">
                                                <button type="submit" class="btn btn-success w-100" id="btnSubmit"
                                                    title="Salvar Subcategoria">
                                                    <i class="fa fa-save pr-1"></i> Salvar
                                                </button>
                                            </div>
                                            <div class="col-md-4 mt-2 mb-2">
                                                <button type="button" class="btn btn-outline-primary w-100"
                                                    onclick="listSubcategories('<?php echo $_POST['category_uuid']; ?>');"
                                                    title="Voltar para Subcategorias">
                                                    <i class="fas fa-arrow-left pr-1"></i> Voltar
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function () {
            $('#formUpdateSubcategory').validate({
                rules: {
                    name: {
                        remote: {
                            type: "post",
                            url: "<?php echo baseUrl; ?>painel/subcategorias/valor-existente",
                            data: {
                                uuid: '<?php echo $_POST['uuid']; ?>',
                                category_uuid: '<?php echo $_POST['category_uuid']; ?>'
                            }
                        }
                    },
                },
                messages: {
                    name: {
                        remote: "Subcategoria já cadastrada"
                    },
                },
                submitHandler: function (form) {
                    let dados = $(form).serialize();

                    $("#baseLoader").show();
                    $("#btnSubmit").attr('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>painel/subcategorias/processa-edicao",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(function (data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                    }).fail(function () {
                        showInternalErrorAlert();
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                    });

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>