<?php
$entity = $this->view->entity;
$dataRand = $this->view->dataRand;
$config = $this->getSiteConfig();
?>
<div class="inner-banner" style="background-image: url('<?php echo $this->getInternalBanner('file_publications'); ?>'); background-size: cover;">
    <section class="w3l-breadcrumb">
        <div class="container">
            <ul class="breadcrumbs-custom-path">
                <li>
                    <h1 style=" color: white; font-size: 40px;">
                        Publicação
                    </h1>
                    <div class="mt-2">
                        <span class="fa fa-chevron-right mx-2" aria-hidden="true"></span> <?php echo $entity['category']; ?>
                    </div>
                </li>
            </ul>
        </div>
    </section>
</div>
<section class="text-11">
    <div class="text11 py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="header-title">
                        <h2 class="hny-title text-left">
                            <?php echo $entity['title']; ?>
                        </h2>
                        <h4 class="mt-2"><?php echo $entity['subtitle']; ?></h4>
                    </div>
                </div>
                <div class="col-md-12">
                    <hr>
                    <div class="row">
                        <div class="col-6 col-md-6 pt-2">
                            <span class="fa fa-calendar"></span> <b>
                                <?php echo $this->formatDateTimeWithLabels($entity['created_at']); ?>
                            </b>
                        </div>
                        <div class="col-6 col-md-6">
                            <div class="main-social-footer-29 text-right">
                                <a id="whatsapp-share-btt" rel="nofollow" target="_blank" class="whatsapp-share-button">
                                    <span class="fa fa-whatsapp"></span>
                                </a>

                                <a id="facebook-share-btt" rel="nofollow" target="_blank" class="facebook-share-button">
                                    <span class="fa fa-facebook">
                                </a>

                                <a id="twitter-share-btt" rel="nofollow" target="_blank" class="twitter-share-button">
                                    <span class="fa fa-twitter"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="col-md-12 pb-3">
                    <?php if (!empty($this->view->files)) : ?>
                        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner" style="box-shadow: 0 0 0.5em <?php echo $config['secondary_color'] ?>;">
                                <?php $i = 0; ?>
                                <?php foreach ($this->view->files as $file) : ?>
                                    <?php $i++; ?>
                                    <div class="carousel-item <?php echo ($i == 1) ? 'active' : ''; ?>">
                                        <img src="<?php echo baseUrl . 'public/uploads/blog/' . $entity['uuid'] . '/' . $file['file']; ?>" class="d-block w-100" alt="<?php echo $entity['title']; ?>" style="width: 100%;">
                                    </div>
                                <?php endforeach; ?>
                            </div>
                            <?php if (count($this->view->files) > 1) : ?>
                                <button class="carousel-control-prev" type="button" data-target="#carouselExampleControls" data-slide="prev" style="background: transparent; border: 0;">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </button>
                                <button class="carousel-control-next" type="button" data-target="#carouselExampleControls" data-slide="next" style="background: transparent; border: 0;">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </button>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="col-md-12 mt-3">
                    <p>
                        <?php echo $entity['description']; ?>
                    </p>

                    <?php if (!empty($entity['source_title']) && empty($entity['source_link'])) : ?>
                        <div class="mt-5">
                            <p>
                                Fonte: <i>
                                    <?php echo $entity['source_title']; ?>
                                </i>
                            </p>
                        </div>
                    <?php elseif (!empty($entity['source_title']) && !empty($entity['source_link'])) : ?>
                        <div class="mt-5">
                            <p>
                                Fonte: <i><a href="<?php echo $entity['source_link']; ?>" target="_blank"><?php echo $entity['source_title']; ?></a></i>
                            </p>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</section>
<?php if (!empty($dataRand)) : ?>
    <section class="w3l-blogpost-content pt-5">
        <div class="container">
            <div class="header-title mb-md-5 mt-4">
                <span class="sub-title">Publicações Relacionadas</span>
                <h3 class="hny-title text-left">Continue Lendo</h3>
            </div>
            <div class="row mt-5">
                <?php foreach ($dataRand as $publication) :
                    $file = $this->getPostFile($entity['uuid']);
                ?>
                    <div class="col-md-6 item mb-5">
                        <div class="card ">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php if (!empty($file)) : ?>
                                        <a href="<?php echo baseUrl . 'post?s=' . $entity['slug']; ?>">
                                            <img src="<?php echo baseUrl . 'public/uploads/blog/' . $file; ?>" alt="<?php echo $entity['title']; ?>" class="img-fluid w-100" style="box-shadow: 0 0 0.5em <?php echo $config['secondary_color'] ?>;">
                                        </a>
                                    <?php else : ?>
                                        <a href="<?php echo baseUrl . 'post?s=' . $entity['slug']; ?>">
                                            <img src="<?php echo baseUrl . 'public/uploads/semfoto.png'; ?>" alt="<?php echo $entity['title']; ?>" class="img-fluid w-100" style="box-shadow: 0 0 0.5em <?php echo $config['secondary_color'] ?>;">
                                        </a>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-12">
                                    <div class="pt-3 ml-3">
                                        <span class="fa fa-calendar"></span> <b>
                                            <?php echo $this->formatDateTimeWithLabels($entity['created_at']); ?>
                                        </b>
                                    </div>
                                    <a href="<?php echo baseUrl . 'post?s=' . $entity['slug']; ?>" class="blog-desc ml-3">
                                        <?php echo $entity['title']; ?>
                                    </a>
                                    <div class="ml-3 pb-3">
                                        <a href="<?php echo baseUrl . 'post?s=' . $entity['slug']; ?>" class="">
                                            <span class="">
                                                <?php echo $entity['subtitle']; ?>
                                            </span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </section>
<?php endif; ?>
<section class="w3l-blogpost-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center mb-5">
                <br>
                <a href="<?php echo baseUrl . 'blog'; ?>" class="btn btn-primary btn-xs mt-3"><span class="fa fa-arrow-left pr-2"></span>Voltar</a>
            </div>
        </div>
    </div>
</section>
<script src="<?php echo baseUrl . 'public/js/jquery.min.js' ?>"></script>
<script type="text/javascript">
    //Constrói a URL depois que o DOM estiver pronto
    document.addEventListener("DOMContentLoaded", function() {
        //conteúdo que será compartilhado: Título da página + URL
        let conteudo = encodeURIComponent("<?php echo $config['site_title']; ?> - <?php echo $entity['title']; ?> " + window.location.href);
        //altera a URL do botão
        document.getElementById("whatsapp-share-btt").href = "https://api.whatsapp.com/send?text=" + conteudo;
    }, false);

    //Constrói a URL depois que o DOM estiver pronto
    document.addEventListener("DOMContentLoaded", function() {
        //altera a URL do botão
        document.getElementById("facebook-share-btt").href = "https://www.facebook.com/sharer/sharer.php?u=" + encodeURIComponent(window.location.href);
    }, false);

    document.addEventListener("DOMContentLoaded", function() {
        let url = encodeURIComponent(window.location.href);
        document.getElementById("twitter-share-btt").href = "https://twitter.com/intent/tweet?url=" + url + "&text=" + "<?php echo $config['site_title']; ?> - <?php echo $entity['title']; ?> ";
        //se for usar o atributo via, utilize a seguinte url
        //document.getElementById("twitter-share-btt").href = "https://twitter.com/intent/tweet?url="+url+"&text="+titulo+"&via="+via;
    }, false);
</script>