<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('update'), $this->moduleCodes('blog'))): ?>
    <?php $entity = $this->view->entity; ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row mb-2">
                <div class="col-11">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-pen-square pr-1"></i>
                        Publicação
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Blog"
                                onclick="openModule('blog');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formUpdateBlog" id="formUpdateBlog"
                                enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="row">
                                                <?php foreach ($this->view->files as $file): ?>
                                                    <div class="col-4 col-md-1 text-center" id="box_<?php echo $file['uuid']; ?>">
                                                        <a href="<?php echo baseUrl . 'public/uploads/blog/' . $entity['uuid'] . '/'
                                                            . $file['file']; ?>" data-lightbox="image-1" data-title="<?php echo $file['file']; ?>">
                                                            <img src="<?php echo baseUrl . 'public/uploads/blog/' . $entity['uuid'] . '/'
                                                                . $file['file']; ?>" alt="img_upload" style="width: 50%;">
                                                        </a>
                                                        <br>
                                                        <a onclick="deleteImage('<?php echo $file['uuid']; ?>');" style="cursor: pointer;" class="mt-3">
                                                            <span class="fa fa-trash"></span>
                                                        </a> 
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>  
                                            <label for="file">Enviar Imagens</label>
                                            <input type="file" class="form-control" name="file[]" id="file" multiple>         
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="title">Título da Publicação*</label>
                                            <input type="text" class="form-control" name="title" id="title" required maxlength="130"
                                                value="<?php echo $entity['title']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="subtitle">Subtítulo*</label>
                                            <input type="text" class="form-control" name="subtitle" id="subtitle" required maxlength="190"
                                                value="<?php echo $entity['subtitle']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="category_uuid">Categoria*</label>
                                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('create'), $this->moduleCodes('categories'))): ?>
                                                <a onclick="newCategory();" class="text-success" 
                                                    style="cursor: pointer; float: right" title="Adicionar Categoria">
                                                    <span class="fa fa-plus-circle"></span>
                                                </a> 
                                            <?php endif; ?>
                                            <select name="category_uuid" id="category_uuid" class="form-control" required
                                                onchange="getSubcategories();">
                                                <option value="">Selecione</option>
                                                <?php foreach ($this->view->categories as $category): ?>
                                                    <option value="<?php echo $category['uuid']; ?>"
                                                        <?php echo (!empty($entity['category_uuid']) && $entity['category_uuid'] == $category['uuid']) 
                                                            ? 'selected' : ''; ?>>
                                                        <?php echo $category['name']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="subcategory_uuid">Subcategoria</label>
                                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('create'), $this->moduleCodes('subcategories'))): ?>
                                                <a onclick="newSubcategory();" class="text-success" 
                                                    style="cursor: pointer; float: right" title="Adicionar Categoria">
                                                    <span class="fa fa-plus-circle"></span>
                                                </a> 
                                            <?php endif; ?>
                                            <select name="subcategory_uuid" id="subcategory_uuid" class="form-control">
                                                <option value="">Selecione</option>
                                                
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="description">Descrição</label>
                                            <textarea name="description" id="description" rows="10" class="form-control"><?php echo $entity['description']; ?></textarea>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="source_title">Fonte</label>
                                            <input type="text" class="form-control" name="source_title" id="source_title" maxlength="100"
                                                value="<?php echo $entity['source_title']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="source_link">Url Fonte</label>
                                            <input type="text" class="form-control" name="source_link" id="source_link"
                                                value="<?php echo $entity['source_link']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-4 ">
                                        <div class="form-group">
                                            <label for="source_link">Situação</label>
                                            <select name="status" id="status_1" class="form-control">
                                                <option value="1" <?php echo ($entity['status'] == '1' ? 'selected' : ''); ?>>Publicação ativa</option>
                                                <option value="0" <?php echo ($entity['status'] == '0' ? 'selected' : ''); ?>>Publicação inativa</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <div class="row">
                                            <div class="col-md-8 mt-2 mb-2">
                                                <input type="hidden" name="uuid" id="id_blog" value="<?php echo $entity['uuid']; ?>">
                                                <button type="submit" class="btn btn-success w-100" id="btnSubmit" title="Salvar Publicação">
                                                    <i class="fa fa-save pr-1"></i> Salvar
                                                </button>
                                            </div>
                                            <div class="col-md-4 mt-2 mb-2">
                                                <button type="button" class="btn btn-outline-primary w-100"
                                                        onclick="openModule('blog');" title="Voltar para Blog">
                                                    <i class="fas fa-arrow-left pr-1"></i> Voltar
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <link rel="stylesheet" type="text/css" href="<?php echo baseUrl; ?>public/admin/tinymce/tinymce.min.css">
    <script src="<?php echo baseUrl; ?>public/admin/tinymce/tinymce.js" type="text/javascript"></script>
    <script>
        $(document).ready(function(){
            tinymce.init({
            selector: 'textarea',
            height: 350,
            plugins: [
                'advlist autolink lists link image charmap print preview anchor textcolor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table contextmenu paste code help wordcount'
            ],
            toolbar: 'insert | undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
            content_css: [
                '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                '//www.tinymce.com/css/codepen.min.css']
            });

            $('#formUpdateBlog').validate({
                rules: {
                    title: {
                        remote: { 
                            type: "post",
                            url: "<?php echo baseUrl; ?>painel/blog/valor-existente",
                            data: {uuid: '<?php echo $_POST['uuid']; ?>'}
                        }
                    },
                },
                messages: {
                    title: {
                        remote: "Título já cadastrado"
                    },
                },
                submitHandler: function(){
                    let form_data = new FormData();

                    $.each($("input[type='file']")[0].files, function(i, file) {
                        form_data.append('file_'+i, file);
                    });

                    form_data.append('title', $("#title").val());    
                    form_data.append('subtitle', $("#subtitle").val());    
                    form_data.append('category_uuid', $("#category_uuid").val());    
                    form_data.append('subcategory_uuid', $("#subcategory_uuid").val());  
                    form_data.append('description', $("#description").val());   
                    form_data.append('source_title', $("#source_title").val());   
                    form_data.append('source_link', $("#source_link").val());   
                    form_data.append('status', $("#status_1").val());       
                    form_data.append('uuid', $("#id_blog").val());    

                    $("#baseLoader").show();
                    $("#btnSubmit").attr('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>painel/blog/processa-edicao",
                        cache: false,
                        contentType: false,
                        processData: false,
                        data: form_data,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type === 'success') {
                            updateBlog('<?php echo $entity['uuid']; ?>');
                        } else {
                            $("#baseLoader").hide();
                            $("#btnSubmit").attr('disabled', false);
                        }
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#baseLoader").hide();   
                        $("#btnSubmit").attr('disabled', false);
                    }); 

                    return false;
                }
            });
        });

        function deleteImage(uuid) {
            $("#box_" + uuid).fadeOut(999);

            $.ajax({
                type: "POST",
                url: "<?php echo baseUrl; ?>painel/blog/remove-imagem",
                data: {
                    uuid: uuid
                },
                async: true
            }); 
        }
    </script>
    <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('create'), $this->moduleCodes('categories'))): ?>
        <script>
            function newCategory() {
                $("#modalGreenMidResult").empty();
                $("#modalGreenMid").modal('hide');
                $("#modalGreenMidTitle").html('<i class="fa fa-plus-circle pr-1"></i> Adicionar Categoria');
                $("#modalGreenMidLoader").show();
                $("#modalGreenMid").modal('show');

                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>painel/blog/cadastrar-categoria",
                    async: true
                }).done(function(data) {
                    $("#modalGreenMidResult").html(data);
                    $("#modalGreenMidLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#modalGreenMidLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('create'), $this->moduleCodes('subcategories'))): ?>
        <script>
            function newSubcategory() {
                if ($("#category_uuid").val() === '') {
                    $("#category_uuid").attr('style', 'border: 1px solid red;').focus();
                } else {
                    $("#modalGreenMidResult").empty();
                    $("#modalGreenMid").modal('hide');
                    $("#modalGreenMidTitle").html('<i class="fa fa-plus-circle pr-1"></i> Adicionar Subcategoria');
                    $("#modalGreenMidLoader").show();
                    $("#modalGreenMid").modal('show');

                    $.ajax({
                        type: 'post',
                        url: "<?php echo baseUrl; ?>painel/blog/cadastrar-subcategoria",
                        data: {
                            category_uuid: $("#category_uuid").val(),
                        },
                        async: true
                    }).done(function(data) {
                        $("#modalGreenMidResult").html(data);
                        $("#modalGreenMidLoader").hide();
                    }).fail(function() {
                        showInternalErrorAlert();
                        $("#modalGreenMidLoader").hide();
                    });
                }
            }
        </script>
    <?php endif; ?>
    <script>
        function getSubcategories() {
            let category_uuid = $("#category_uuid").val();
            if (category_uuid !== '') {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>painel/blog/subcategorias",
                    data: {
                        category_uuid: category_uuid,
                        subcategory_uuid: '<?php echo $entity['subcategory_uuid']; ?>'
                    },
                    async: true
                }).done(function(data) {
                    $("#subcategory_uuid").html(data);
                    $("#baseLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            } else {
                $("#subcategory_uuid").html('<option value="">Selecione</option>');
            }
        }

        getSubcategories();
    </script>
<?php endif; ?>