<div class="inner-banner" style="background-image: url('<?php echo $this->getInternalBanner('file_politics'); ?>'); background-size: cover;">
    <section class="w3l-breadcrumb">
        <div class="container">
            <ul class="breadcrumbs-custom-path">
            <li class="active" style="font-size: 40px; text-shadow: black 0.1em 0.1em 0.2em;"> Política de Privacidade</li>
            </ul>
        </div>
    </section>
</div>
<!-- contact1 -->
<section class="w3l-index3" id="about1">
    <div class="midd-w3 py-5">
        <div class="container py-lg-5 py-md-3">
            <div class="row">
                <div class="col-lg-12 mb-lg-0 mb-md-5 mb-4">
                    <?php echo $this->view->entity['description']; ?>
                </div>
            </div>
        </div>
    </div>
</section>