<?php
$data = $this->view->data;

$isAdmin = $_SESSION['ROLE_ADM'] == '1';
$role = $_SESSION['ROLE'];

$canView = $isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('banners'));
$canCreate = $isAdmin || $this->acl($role, $this->resourceCodes('create'), $this->moduleCodes('banners'));
$canUpdate = $isAdmin || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('banners'));
$canDelete = $isAdmin || $this->acl($role, $this->resourceCodes('delete'), $this->moduleCodes('banners'));
?>
<?php if ($canView): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row mb-2">
                <div class="col-10">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-image pr-1"></i>
                        Banners
                    </h1>
                </div>
                <div class="col-2">
                    <?php if ($canCreate): ?>
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item">
                                <button type="button" class="btn btn-outline-success w-100" title="Adicionar Banner"
                                    onclick="createBanner();" style="position: relative; top: 3px">
                                    <i class="fas fa-plus"></i>
                                </button>
                            </li>
                        </ol>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover" id="table_banner" style="width: 99.9%;">
                                    <thead>
                                        <tr class="text-center" style="height: 30px;">
                                            <th style="font-size: 14px;"><span class="fa fa-image"></span></th>
                                            <th style="font-size: 14px;">Título</th>
                                            <th style="font-size: 14px;">Legenda</th>
                                            <th style="font-size: 14px;">Situação</th>
                                            <th style="display: none;">Situação</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($data as $entity): ?>
                                            <tr class="text-center" style="cursor: pointer;"
                                                onclick="openDetails('<?php echo $entity['uuid']; ?>');">
                                                <td style="font-size: 15px">
                                                    <img src="<?php echo baseUrl . 'public/uploads/banner/'
                                                        . $entity['file']; ?>" alt="" style="width:150px;">
                                                </td>
                                                <td class="pt-4" style="font-size: 15px">
                                                    <?php echo $entity['title'] ? $entity['title'] : 'Não informado'; ?>
                                                </td>
                                                <td class="pt-4" style="font-size: 15px">
                                                    <?php echo $entity['caption'] ? $entity['caption'] : 'Não informado'; ?>
                                                </td>
                                                <td class="pt-4" style="width: 80px;">
                                                    <?php if ($entity['status'] == '1'): ?>
                                                        <i class="fa fa-circle" style="color: green;"></i>
                                                    <?php else: ?>
                                                        <i class="fa fa-circle" style="color: red;"></i>
                                                    <?php endif; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo ($entity['status'] == '1') ? 'Ativo' : 'Inativo'; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#table_banner').DataTable({
                "sDom": 'fltip',
                searching: true,
                columnDefs: [{ orderable: false, targets: [0, 3] }],
                responsive: true,
                info: true,
                processing: true,
                scrollCollapse: true,
                paging: true,
                "pageLength": 25,
                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ &nbsp;",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Filtrar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });

        function openDetails(uuid) {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>painel/banner/detalhes",
                data: { uuid: uuid },
                async: true
            }).done(function (data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function () {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }
    </script>
    <?php if ($canCreate): ?>
        <script>
            function createBanner() {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>painel/banner/cadastrar",
                    async: true
                }).done(function (data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canUpdate): ?>
        <script>
            function updateBanner(uuid) {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>painel/banner/editar",
                    data: { uuid: uuid },
                    async: true
                }).done(function (data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canDelete): ?>
        <script>
            function deleteBanner(uuid) {
                $("#modalXL").modal('hide');
                $("#modalDeleteTitle").html('<i class="fa fa-trash pr-2"></i> Remover Banner');
                $("#modalDeleteLoader").hide();
                $("#modalDelete").modal('show');
                $("#modalDeleteResult").html('<button type="button" class="btn btn-danger" title="Confirmar remoção" onclick="runDelete(\'' + uuid + '\');"><i class="fa fa-trash"></i> CONFIRMAR E EXCLUIR</button>');
            }

            function runDelete(uuid) {
                if (uuid !== null) {
                    $("#modalDeleteLoader").show();

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>painel/banner/excluir",
                        data: { uuid: uuid },
                        dataType: 'json',
                        async: true
                    }).done(function (data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#modalDelete").modal('hide');
                        $("#modalXL").modal('hide');
                        openModule('banner');
                    }).fail(function () {
                        showInternalErrorAlert();
                        $("#modalDeleteLoader").hide();
                    });
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>