<?php
$seo = $this->getSiteSeo();
$config = $this->getSiteConfig();
$entity = $this->view->entity;
?>
<div class="inner-banner" style="background-image: url('<?php echo $this->getInternalBanner('file_about'); ?>'); background-size: cover;">
    <section class="w3l-breadcrumb">
        <div class="container">
            <ul class="breadcrumbs-custom-path">
                <li>
                    <h1 style=" color: white; font-size: 40px;"><?php echo $seo['about_title']; ?></h1>
                    <div class="mt-2">
                        <span class="fa fa-chevron-right mx-2" aria-hidden="true"></span> <?php echo $seo['about_description']; ?>
                    </div>
                </li>
            </ul>
        </div>
    </section>
</div>
<section class="w3l-index3 bg-white" id="about1">
    <div class="midd-w3 py-5">
        <div class="container py-lg-5 py-md-3">
            <div class="row">
                <div class="col-md-4 mb-lg-0 mb-md-5 mb-4">
                    <?php if (!empty($entity['file_1'])) : ?>
                        <img src="<?php echo baseUrl . 'public/uploads/about/' . $entity['file_1']; ?>" alt="<?php echo $entity['title_1']; ?>" class="radius-image img-fluid w-100" style="box-shadow: 0 0 0.5em <?php echo $config['secondary_color'] ?>;">
                    <?php else : ?>
                        <img src="<?php echo baseUrl . 'public/uploads/semfoto.png'; ?>" alt="<?php echo $entity['title_1']; ?>" class="radius-image img-fluid w-100" style="box-shadow: 0 0 0.5em <?php echo $config['secondary_color'] ?>;">
                    <?php endif; ?>
                </div>
                <div class="col-md-8 pl-lg-5 ">
                    <div class="header-title">
                        <h3 class="hny-title text-left">
                            <?php echo $entity['title_1']; ?>
                        </h3>
                    </div>
                    <p class="mt-3">
                        <?php echo $entity['description_1']; ?>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<?php if ($entity['block_banner']) : ?>
    <section class="w3l-form-25-section" id="subscribe" style="background: url('<?php echo baseUrl . 'public/uploads/about/' . $entity['block_banner']; ?>');">
        <div class="form-25-mian">
            <div class="container py-5">
                <div class="row subscription-grids py-5">
                    <div class="col-md-7 subscription-left forms-25-info">
                        <?php if (!empty($entity['block_button_link'])) : ?>
                            <div class="header-title">
                                <h3 class="p-0">
                                    <?php echo $entity['block_title']; ?>
                                </h3>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="col-md-5 subscription-right pl-lg-5 mt-lg-0 mt-4 text-lg-right">
                        <?php if (!empty($entity['block_button_link'])) : ?>
                            <a href="<?php echo $entity['block_button_link']; ?>" class="btn btn-style btn-primary mr-lg-4 mr-sm-3">
                                <?php echo $entity['block_button_title']; ?> <span class="fa fa-chevron-right ml-2" aria-hidden="true"></span></a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
    </section>
<?php endif; ?>
<section class="w3l-servicesblock bg-white py-5" id="about">
    <div class="container py-md-5 py-md-3">
        <div class="row">
            <div class="col-md-6 about-right-faq align-self mb-lg-0 mb-sm-5 mb-4 pr-lg-5">
                <div class="header-titlee mb-md-5 mb-4">
                    <h3 class="hny-title text-left">
                        <?php echo $entity['title_2']; ?>
                    </h3>
                </div>
                <div class="mt-md-0 mt-md-5 mt-4">
                    <div class="grids_info">
                        <p class="">
                            <?php echo $entity['description_2']; ?>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 left-wthree-img mt-lg-0 mt-4">
                <?php if (!empty($entity['file_2'])) : ?>
                    <img src="<?php echo baseUrl . 'public/uploads/about/' . $entity['file_2']; ?>" alt="<?php echo $entity['title_2']; ?>" class="img-fluid radius-image w-100" style="box-shadow: 0 0 0.5em <?php echo $config['secondary_color'] ?>;">
                <?php else : ?>
                    <img src="<?php echo baseUrl . 'public/uploads/semfoto.png'; ?>" alt="<?php echo $entity['title_2']; ?>" class="img-fluid radius-image w-100" style="box-shadow: 0 0 0.5em <?php echo $config['secondary_color'] ?>;">
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
<script src="<?php echo baseUrl . 'public/js/jquery.min.js' ?>"></script>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
        let conteudo = encodeURIComponent("<?php echo $config['site_title']; ?> - Sobre Nós " + window.location.href);
        document.getElementById("whatsapp-share-btt").href = "https://api.whatsapp.com/send?text=" + conteudo;
    }, false);
    document.addEventListener("DOMContentLoaded", function() {
        document.getElementById("facebook-share-btt").href = "https://www.facebook.com/sharer/sharer.php?u=" + encodeURIComponent(window.location.href);
    }, false);
    document.addEventListener("DOMContentLoaded", function() {
        let url = encodeURIComponent(window.location.href);
        document.getElementById("twitter-share-btt").href = "https://twitter.com/intent/tweet?url=" + url + "&text=" + "<?php echo $config['site_title']; ?> - <?php echo $seo['title']; ?>";
    }, false);
</script>