<?php
$config = $this->getSiteConfig();
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Validar Código |
        <?php echo $config['site_title']; ?>
    </title>
    <meta author="João Augusto Bonfante">
    <link rel="icon" href="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo_icon']; ?>"
        type="image/x-icon" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/dist/css/adminlte.min.css">
    <link rel="stylesheet"
        href="<?php echo baseUrl; ?>public/admin/plugins/jquery-toast-plugin/dist/jquery.toast.min.css">
    <style>
        h1 {
            color:
                <?php echo $config['primary_color']; ?>
                !important;
        }

        .bg-primary {
            background:
                <?php echo $config['primary_color']; ?>
                !important;
        }

        .bg-primary:hover {
            background:
                <?php echo $config['secondary_color']; ?>
                !important;
        }

        .bg-secondary {
            background:
                <?php echo $config['secondary_color']; ?>
                !important;
        }

        .bg-secondary:hover {
            background:
                <?php echo $config['primary_color']; ?>
                !important;
        }

        .btn-primary {
            background:
                <?php echo $config['primary_color']; ?>
                !important;
        }

        .btn-primary:hover {
            background:
                <?php echo $config['secondary_color']; ?>
                !important;
        }

        .btn-secondary {
            background:
                <?php echo $config['secondary_color']; ?>
                !important;
        }

        .btn-secondary:hover {
            background:
                <?php echo $config['primary_color']; ?>
                !important;
        }
    </style>
</head>

<body class="hold-transition login-page">
    <div class="login-box">
        <div class="card card-outline card-dark">
            <div class="card-header text-center">
                <img src="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo']; ?>" alt="logo"
                    style="width: 100%;">
            </div>
            <div class="card-body">
                <p class="login-box-msg">Informe código recebido</p>
                <form action="<?php echo baseUrl; ?>painel/validar-codigo" method="post" id="formValidateCode"
                    onsubmit="hashPass(this);">
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Código" name="code" id="code" required>
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 mt-1">
                            <button type="submit" class="btn btn-primary btn-block"
                                id="btnConfirmCode">Confirmar</button>
                        </div>
                        <div class="col-12 text-center mt-2">
                            <a href="<?php echo baseUrl; ?>painel/esqueci-a-senha" style=" color: #000;">
                                Voltar
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="<?php echo baseUrl; ?>public/admin/plugins/jquery/jquery.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/dist/js/adminlte.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/plugins/jquery-toast-plugin/dist/jquery.toast.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/alerts.js"></script>
    <script src="<?php echo baseUrl; ?>public/js/md5.min.js"></script>
    <div class="modal fade" id="modalLoad" data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div style="font-size: 20px; color: <?php echo $config['secondary_color'] ?>">
                        <span class="fa fa-clock"></span> Aguarde...
                    </div>
                    <hr>
                    <h2>Validando Código</h2>
                </div>
            </div>
        </div>
    </div>
    <script>
        function hashPass(form) {
            if (form.code.value !== '') {
                form.code.value = md5(form.code.value);
                $("#btnConfirmCode").attr('disabled', true);
                $("#modalLoad").modal('show');
            } else {
                $("#btnConfirmCode").attr('disabled', false);
                $("#modalLoad").modal('hide');
            }
        }
    </script>
    <?php if (!empty($_GET['msg']) && $_GET['msg'] == 'codigo-invalido'): ?>
        <script>
            showAlert('error', 'Ops!', 'Código inválido, tente novamente.', 'top-center');
        </script>
    <?php endif; ?>

</html>