<?php
$config = $this->getSiteConfig();
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Validar Código |
        <?php echo $config['site_title']; ?>
    </title>
    <meta author="João Augusto Bonfante">
    <link rel="icon" href="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo_icon']; ?>"
        type="image/x-icon" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/dist/css/adminlte.min.css">
    <link rel="stylesheet"
        href="<?php echo baseUrl; ?>public/admin/plugins/jquery-toast-plugin/dist/jquery.toast.min.css">
    <style>
        h1 {
            color:
                <?php echo $config['primary_color']; ?>
                !important;
        }

        .btn-primary {
            background:
                <?php echo $config['primary_color']; ?>
                !important;
        }

        .btn-primary:hover {
            background:
                <?php echo $config['secondary_color']; ?>
                !important;
        }
    </style>
</head>

<body class="hold-transition login-page">
    <div class="login-box">
        <div class="card card-outline card-dark">
            <div class="card-header text-center">
                <img src="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo']; ?>" alt="logo"
                    style="width: 100%;">
            </div>
            <div class="card-body">
                <p class="login-box-msg">Informe o token que foi enviado para <b>
                        <?php echo $_SESSION['EMAIL']; ?>
                    </b></p>
                <form action="<?php echo baseUrl; ?>painel/validar-token" method="post" id="formLoginToken"
                    onsubmit="hashPass(this);">
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Código" name="token" id="token"
                            required maxlength="10">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="checkbox" placeholder="Código" name="remember" id="remember" value="1">
                        <div class="input-group-append pl-1">
                            Lembrar neste dispositivo
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 mt-1">
                            <button type="submit" class="btn btn-primary btn-block" id="btnSubmitToken">Validar</button>
                        </div>
                        <div class="col-12 text-center mt-3">
                            <a href="<?php echo baseUrl; ?>painel/cancelar-token" style=" color: #000;">
                                Cancelar
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="<?php echo baseUrl; ?>public/admin/plugins/jquery/jquery.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/dist/js/adminlte.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/plugins/jquery-toast-plugin/dist/jquery.toast.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/alerts.js"></script>
    <script src="<?php echo baseUrl; ?>public/js/md5.min.js"></script>
    <div class="modal fade" id="modalLoad" data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div style="font-size: 20px; color: <?php echo $config['secondary_color'] ?>">
                        <span class="fa fa-clock"></span> Aguarde...
                    </div>
                    <hr>
                    <h2>Autenticando Informações</h2>
                </div>
            </div>
        </div>
    </div>
    <script>
        function hashPass(form) {
            if (form.token.value !== '') {
                form.token.value = md5(form.token.value);
                $("#btnSubmitToken").attr('disabled', true);
                $("#modalLoad").modal('show');
            } else {
                $("#btnSubmitToken").attr('disabled', false);
                $("#modalLoad").modal('hide');
            }
        }
    </script>
    <?php if (!empty($_GET['msg']) && $_GET['msg'] == 'token-invalido'): ?>
        <script>
            showAlert('error', 'Ops!', 'Token inválido, tente novamente.', 'top-center');
        </script>
    <?php endif; ?>

</html>