<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('update'), $this->moduleCodes('services'))): ?>
    <?php $entity = $this->view->entity; ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row mb-2">
                <div class="col-11">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-pen-square pr-1"></i>
                        Serviço
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Serviços"
                                onclick="openModule('servicos');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i>
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formUpdateService" id="formUpdateService"
                                enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="row">
                                                <?php foreach ($this->view->files as $file): ?>
                                                    <div class="col-4 col-md-1 text-center"
                                                        id="box_<?php echo $file['uuid']; ?>">
                                                        <a href="<?php echo baseUrl . 'public/uploads/services/' . $entity['uuid'] . '/'
                                                            . $file['file']; ?>" data-lightbox="image-1" data-title="<?php echo $file['file']; ?>">
                                                            <img src="<?php echo baseUrl . 'public/uploads/services/' . $entity['uuid'] . '/'
                                                                . $file['file']; ?>" alt="img_upload"
                                                                style="width: 50%;">
                                                        </a>
                                                        <br>
                                                        <a onclick="deleteImage('<?php echo $file['uuid']; ?>');"
                                                            style="cursor: pointer;" class="mt-3">
                                                            <span class="fa fa-trash"></span>
                                                        </a>
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                            <label for="file">Enviar Imagens</label>
                                            <input type="file" class="form-control" name="file[]" id="file" multiple>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="title">Título*</label>
                                            <input type="text" class="form-control" name="title" id="title" required
                                                value="<?php echo $entity['title']; ?>" maxlength="25">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="description">Descrição</label>
                                            <textarea name="description" id="description" rows="10"
                                                class="form-control"><?php echo $entity['description']; ?></textarea>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="description">Situação</label>
                                            <select name="status" id="status_1" class="form-control">
                                                <option value="1" <?php echo ($entity['status'] == '1' ? 'selected' : ''); ?>>
                                                    Serviço ativo</option>
                                                <option value="0" <?php echo ($entity['status'] == '0' ? 'selected' : ''); ?>>
                                                    Serviço inativo</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="row">
                                            <div class="col-md-8 mt-2 mb-2">
                                                <input type="hidden" name="uuid" id="id_servicos"
                                                    value="<?php echo $entity['uuid']; ?>">
                                                <button type="submit" class="btn btn-success w-100" id="btnSubmit"
                                                    title="Salvar Serviço">
                                                    <i class="fa fa-save pr-1"></i> Salvar
                                                </button>
                                            </div>
                                            <div class="col-md-4 mt-2 mb-2">
                                                <button type="button" class="btn btn-outline-primary w-100"
                                                    onclick="openModule('servicos');" title="Voltar para Serviços">
                                                    <i class="fas fa-arrow-left pr-1"></i> Voltar
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <link rel="stylesheet" type="text/css" href="<?php echo baseUrl; ?>public/admin/tinymce/tinymce.min.css">
    <script src="<?php echo baseUrl; ?>public/admin/tinymce/tinymce.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            tinymce.init({
                selector: 'textarea',
                height: 350,
                plugins: [
                    'advlist autolink lists link image charmap print preview anchor textcolor',
                    'searchreplace visualblocks code fullscreen',
                    'insertdatetime media table contextmenu paste code help wordcount'
                ],
                toolbar: 'insert | undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
                content_css: [
                    '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                    '//www.tinymce.com/css/codepen.min.css']
            });

            $('#formUpdateService').validate({
                rules: {
                    title: {
                        remote: {
                            type: "post",
                            url: "<?php echo baseUrl; ?>painel/servicos/valor-existente",
                            data: { uuid: '<?php echo $_POST['uuid']; ?>' }
                        }
                    },
                },
                messages: {
                    title: {
                        remote: "Serviço já cadastrado"
                    },
                },
                submitHandler: function () {
                    let form_data = new FormData();

                    $.each($("input[type='file']")[0].files, function (i, file) {
                        form_data.append('file_' + i, file);
                    });

                    form_data.append('title', $("#title").val());
                    form_data.append('description', $("#description").val());
                    form_data.append('status', $("#status_1").val());
                    form_data.append('uuid', $("#id_servicos").val());

                    $("#baseLoader").show();
                    $("#btnSubmit").show('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>painel/servicos/processa-edicao",
                        cache: false,
                        contentType: false,
                        processData: false,
                        data: form_data,
                        dataType: 'json',
                        async: true
                    }).done(function (data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type === 'success') {
                            updateService('<?php echo $entity['uuid']; ?>');
                        } else {
                            $("#baseLoader").hide();
                            $("#btnSubmit").show('disabled', false);
                        }
                    }).fail(function () {
                        showInternalErrorAlert();
                        $("#baseLoader").hide();
                        $("#btnSubmit").show('disabled', false);
                    });

                    return false;
                }
            });
        });

        function deleteImage(uuid) {
            $("#box_" + uuid).fadeOut(999);

            $.ajax({
                type: "POST",
                url: "<?php echo baseUrl; ?>painel/servicos/remove-imagem",
                data: {
                    uuid: uuid
                },
                async: true
            });
        }
    </script>
<?php endif; ?>