<?php 
$entity = $this->view->entity; 

$canView    = $_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('about'));
$canUpdate  = $_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('update'), $this->moduleCodes('about'));
?>
<?php if ($canView): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row mb-2">
                <div class="col-11">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-pen pr-1"></i>
                        Empresa
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <a href="<?php echo baseUrl . 'painel'; ?>" class="btn btn-outline-primary w-100" title="Página Inical">
                                <i class="fas fa-home"></i> 
                            </a>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formUpdateAbout" id="formUpdateAbout"
                                enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-md-12 text-center">
                                        <hr>
                                        <h3>Imagem <b>Bloco 1</b></h3>
                                        <hr>
                                    </div>
                                    <div class="col-md-4 offset-md-4">
                                        <div class="form-group">
                                            <?php if (!empty($entity['file_1'])): ?>
                                                <div class="text-center mb-3">
                                                    <a href="<?php echo baseUrl . 'public/uploads/about/'
                                                        . $entity['file_1']; ?>" data-lightbox="image-1" data-title="<?php echo $entity['file_1']; ?>">
                                                        <img src="<?php echo baseUrl . 'public/uploads/about/'
                                                            . $entity['file_1']; ?>" alt="" style="width: 100%;">
                                                    </a>
                                                    <?php if ($canUpdate): ?>
                                                        <div class="my-2">
                                                            <input type="checkbox" name="remove_image" id="remove_image" value="1"> Remover imagem
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($canUpdate): ?>
                                                <label for="file_1">Imagem</label>
                                                <input type="file" class="form-control" name="file_1" id="file_1">         
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <div class="col-md-12 text-center">
                                        <hr>
                                        <h3>Texto <b>Bloco 1</b></h3>
                                        <hr>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label for="title_1">Título*</label>
                                                    <input type="text" class="form-control" name="title_1" id="title_1"  <?php echo ($canUpdate) ? 'required' : 'readonly'; ?> maxlength="200"
                                                        value="<?php echo $entity['title_1']; ?>">
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label for="description_1">Descrição</label>
                                                    <textarea name="description_1" id="description_1" rows="12" class="form-control"  <?php echo ($canUpdate) ? 'required' : 'readonly'; ?>
                                                        ><?php echo $entity['description_1']; ?></textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div> 
                                    <div class="col-md-12"><hr></div>
                                    <div class="col-md-12 text-center">
                                        <hr>
                                        <h3>Imagem <b>Bloco 2</b></h3>
                                        <hr>
                                    </div>
                                    <div class="col-md-4 offset-md-4">
                                        <div class="form-group">
                                            <?php if (!empty($entity['file_2'])): ?>
                                                <div class="text-center mb-3">
                                                    <a href="<?php echo baseUrl . 'public/uploads/about/'
                                                        . $entity['file_2']; ?>" data-lightbox="image-1" data-title="<?php echo $entity['file_2']; ?>">
                                                        <img src="<?php echo baseUrl . 'public/uploads/about/'
                                                            . $entity['file_2']; ?>" alt="" style="width: 100%;">
                                                    </a>
                                                    <?php if ($canUpdate): ?>
                                                        <div class="my-2">
                                                            <input type="checkbox" name="remove_image_2" id="remove_image_2" value="1"> Remover imagem
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($canUpdate): ?>
                                                <label for="file_2">Imagem</label>
                                                <input type="file" class="form-control" name="file_2" id="file_2">         
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <div class="col-md-12 text-center">
                                        <hr>
                                        <h3>Textos <b>Bloco 2</b></h3>
                                        <hr>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label for="title_2">Título*</label>
                                                    <input type="text" class="form-control" name="title_2" id="title_2"  <?php echo ($canUpdate) ? 'required' : 'readonly'; ?> maxlength="200"
                                                        value="<?php echo $entity['title_2']; ?>">
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <textarea name="description_2" id="description_2" rows="11" class="form-control" 
                                                    <?php echo ($canUpdate) ? 'required' : 'readonly'; ?>><?php echo $entity['description_2']; ?></textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12 text-center">
                                        <hr>
                                        <h3>Bloco Central</b></h3>
                                        <hr>
                                    </div>
                                    <div class="col-md-6 offset-md-3">
                                        <div class="form-group">
                                            <?php if (!empty($entity['block_banner'])): ?>
                                                <div class="text-center mb-3">
                                                    <a href="<?php echo baseUrl . 'public/uploads/about/'
                                                        . $entity['block_banner']; ?>" data-lightbox="image-1" data-title="<?php echo $entity['block_banner']; ?>">
                                                        <img src="<?php echo baseUrl . 'public/uploads/about/'
                                                            . $entity['block_banner']; ?>" alt="" style="width: 100%;">
                                                    </a>
                                                    <?php if ($canUpdate): ?>
                                                        <div class="my-2">
                                                            <input type="checkbox" name="remove_image_banner" id="remove_image_banner" value="1"> Remover imagem
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($canUpdate): ?>
                                                <label for="block_banner">Imagem</label>
                                                <input type="file" class="form-control" name="block_banner" id="block_banner">         
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="block_title">Título</label>
                                            <input type="text" class="form-control" name="block_title" id="block_title" maxlength="200" <?php echo ($canUpdate) ? '' : 'readonly'; ?>
                                                value="<?php echo $entity['block_title']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="block_button_title">Título do Botão</label>
                                            <input type="text" class="form-control" name="block_button_title" id="block_button_title" maxlength="50"
                                                value="<?php echo $entity['block_button_title']; ?>" <?php echo ($canUpdate) ? '' : 'readonly'; ?>>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="block_button_link">Link do Botão</label>
                                            <input type="text" class="form-control" name="block_button_link" id="block_button_link"
                                                value="<?php echo $entity['block_button_link']; ?>" <?php echo ($canUpdate) ? '' : 'readonly'; ?>>
                                        </div>
                                    </div>
                                    <?php if ($canUpdate): ?>
                                        <div class="col-md-8 mt-2 mb-2">
                                            <button type="submit" class="btn btn-success w-100" id="btnSubmit" title="Salvar">
                                                <i class="fa fa-save pr-1"></i> Salvar
                                            </button>
                                        </div>
                                        <div class="col-md-4 mt-2 mb-2">
                                            <a href="<?php echo baseUrl . 'painel'; ?>" class="btn btn-outline-primary w-100" title="Página Inicial">
                                                <i class="fas fa-home pr-1"></i> Início
                                            </a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php if ($canUpdate): ?>
        <link rel="stylesheet" type="text/css" href="<?php echo baseUrl; ?>public/admin/tinymce/tinymce.min.css">
        <script src="<?php echo baseUrl; ?>public/admin/tinymce/tinymce.js" type="text/javascript"></script>
        <script>
            $(document).ready(function(){
                tinymce.init({
                selector: 'textarea',
                height: 350,
                plugins: [
                    'advlist autolink lists link image charmap print preview anchor textcolor',
                    'searchreplace visualblocks code fullscreen',
                    'insertdatetime media table contextmenu paste code help wordcount'
                ],
                toolbar: 'insert | undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
                content_css: [
                    '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                    '//www.tinymce.com/css/codepen.min.css']
                });
                $('#formUpdateAbout').validate({
                    submitHandler: function(){
                        let file_1 = $('#file_1').prop('files')[0];
                        let file_2 = $('#file_2').prop('files')[0];   
                        let block_banner = $('#block_banner').prop('files')[0];   
                        let form_data = new FormData();         

                        form_data.append('title_1', $("#title_1").val());    
                        form_data.append('description_1', $("#description_1").val());    
                        form_data.append('file_1', file_1);    
                        form_data.append('title_2', $("#title_2").val());    
                        form_data.append('description_2', $("#description_2").val());    
                        form_data.append('file_2', file_2);       
                        form_data.append('block_banner', block_banner);   
                        form_data.append('block_title', $("#block_title").val());   
                        form_data.append('block_button_title', $("#block_button_title").val());   
                        form_data.append('block_button_link', $("#block_button_link").val());   
                        
                        if ($('#remove_image').is(':checked')) {
                            form_data.append('remove_image', $("#remove_image").val());    
                        }
                        
                        if ($('#remove_image_2').is(':checked')) {
                            form_data.append('remove_image_2', $("#remove_image_2").val());    
                        }

                        if ($('#remove_image_banner').is(':checked')) {
                            form_data.append('remove_image_banner', $("#remove_image_banner").val());    
                        }

                        $("#baseLoader").show();
                        $("#btnSubmit").attr('disabled', true);

                        $.ajax({
                            type: "POST",
                            url: "<?php echo baseUrl; ?>painel/empresa/processa-edicao",
                            cache: false,
                            contentType: false,
                            processData: false,
                            data: form_data,
                            dataType: 'json',
                            async: true
                        }).done(function(data) {
                            showAlert(data.type, data.title, data.msg, data.pos);
                                window.location.href = "<?php echo baseUrl; ?>painel?mod=empresa";
                        }).fail(function() {
                            showInternalErrorAlert(); 
                            $("#baseLoader").hide();   
                            $("#btnSubmit").attr('disabled', false);
                        }); 
    
                        return false;
                    }
                });
            });
        </script>
    <?php endif; ?>
<?php endif; ?>