<?php
$config = $this->getSiteConfig();

$canViewUsers = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('user'));
$canViewConfigs = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('configs'));
$canViewLogs = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('logs'));
$canViewSeo = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('seo'));
$canViewHome = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('home'));
$canViewBanners = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('banners'));
$canViewInternalBanners = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('internal-banners'));
$canViewAbout = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('about'));
$canViewPublications = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('blog'));
$canViewTestimonials = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('testimonials'));
$canViewNewsletter = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('newsletter'));
$canViewCategories = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('categories'));
$canViewCustomers = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('customers'));
$canViewSmtp = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('smtp'));
$canViewServices = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('services'));
$canViewPolitics = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('politics'));
$canViewUseTerms = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('use-terms'));
$canViewImporter = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('importer'));

$config['logo'] = !empty($config['logo']) ? $config['logo'] : 'jaconsultoriati.png';
$config['logo_icon'] = !empty($config['logo_icon']) ? $config['logo_icon'] : 'jaconsultoriati.png';
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PAINEL |
        <?php echo $config['site_title']; ?>
    </title>
    <meta author="João Augusto Bonfante">
    <link rel="icon" href="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo_icon']; ?>" type="image/x-icon" />
    <meta name="robots" content="noindex">
    <meta name="googlebot" content="noindex">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/dist/css/adminlte.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <link href="<?php echo baseUrl; ?>public/admin/css/buttons.dataTables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/css/dataTables.bootstrap4.min.css">
    <script src="<?php echo baseUrl; ?>public/admin/plugins/jquery/jquery.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/dist/js/adminlte.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/jquery.maskMoney.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/jquery.maskedinput.js" type="text/javascript"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/jquery.validate.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/jquery.inputmask.js"></script>
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/plugins/jquery-toast-plugin/dist/jquery.toast.min.css">
    <script src="<?php echo baseUrl; ?>public/admin/plugins/jquery-toast-plugin/dist/jquery.toast.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/alerts.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/jquery.dataTables.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/dataTables.bootstrap4.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/date-eu.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/date-eu-com-filtro.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/dataTables.valoremreais.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/dataTables.buttons.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/jszip.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/pdfmake.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/vfs_fonts.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/buttons.html5.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/js/buttons.print.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/admin/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo baseUrl; ?>public/admin/plugins/select2/css/select2.min.css">
    <script src="<?php echo baseUrl; ?>public/admin/plugins/select2/js/select2.min.js"></script>

    <link href="<?php echo baseUrl; ?>public/lightbox2/src/css/lightbox.css" rel="stylesheet" />
    <script src="<?php echo baseUrl; ?>public/lightbox2/src/js/lightbox.js"></script>
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <style>
        .pst {}

        h1 {
            color:
                <?php echo $config['primary_color']; ?> !important;
        }

        .bg-primary {
            background:
                <?php echo $config['primary_color']; ?> !important;
        }

        .bg-primary:hover {
            background:
                <?php echo $config['secondary_color']; ?> !important;
        }

        .bg-secondary {
            background:
                <?php echo $config['secondary_color']; ?> !important;
        }

        .bg-secondary:hover {
            background:
                <?php echo $config['primary_color']; ?> !important;
        }

        .btn-primary {
            background:
                <?php echo $config['primary_color']; ?> !important;
        }

        .btn-primary:hover {
            background:
                <?php echo $config['secondary_color']; ?> !important;
        }

        .btn-secondary {
            background:
                <?php echo $config['secondary_color']; ?> !important;
        }

        .btn-secondary:hover {
            background:
                <?php echo $config['primary_color']; ?> !important;
        }

        .page-link:hover {
            z-index: 2;
            color: #fff;
            text-decoration: none;
            background-color:
                <?php echo $config['secondary_color']; ?>;
            border-color:
                <?php echo $config['secondary_color']; ?>;
        }


        .page-item.active .page-link {
            z-index: 3;
            color: #fff;
            background-color:
                <?php echo $config['primary_color']; ?> !important;
            ;
            border-color:
                <?php echo $config['primary_color']; ?> !important;
            ;
        }


        .btn-outline-primary {
            color:
                <?php echo $config['primary_color']; ?>;
            border-color:
                <?php echo $config['primary_color']; ?>;
        }

        .btn-outline-primary:hover {
            color: #fff;
            background-color:
                <?php echo $config['primary_color']; ?>;
            border-color:
                <?php echo $config['primary_color']; ?>;
        }

        .btn-outline-primary.disabled,
        .btn-outline-primary:disabled {
            color:
                <?php echo $config['primary_color']; ?>;
            background-color: transparent;
        }

        .btn-outline-primary:not(:disabled):not(.disabled):active,
        .btn-outline-primary:not(:disabled):not(.disabled).active,
        .show>.btn-outline-primary.dropdown-toggle {
            color: #fff;
            background-color:
                <?php echo $config['primary_color']; ?>;
            border-color:
                <?php echo $config['primary_color']; ?>;
        }

        .btn-outline-secondary {
            color:
                <?php echo $config['secondary_color']; ?>;
            border-color:
                <?php echo $config['secondary_color']; ?>;
        }

        .btn-outline-secondary:hover {
            color: #fff;
            background-color:
                <?php echo $config['secondary_color']; ?>;
            border-color:
                <?php echo $config['secondary_color']; ?>;
        }

        .btn-outline-secondary.disabled,
        .btn-outline-secondary:disabled {
            color:
                <?php echo $config['secondary_color']; ?>;
            background-color: transparent;
        }

        .btn-outline-secondary:not(:disabled):not(.disabled):active,
        .btn-outline-secondary:not(:disabled):not(.disabled).active,
        .show>.btn-outline-secondary.dropdown-toggle {
            color: #fff;
            background-color:
                <?php echo $config['secondary_color']; ?>;
            border-color:
                <?php echo $config['secondary_color']; ?>;
        }

        .bg-gradient-primary {
            background:
                <?php echo $config['secondary_color']; ?> linear-gradient(180deg,
                    <?php echo $config['primary_color']; ?>,
                    <?php echo $config['secondary_color']; ?>) repeat-x !important;
            color: #fff;
        }

        .bg-gradient-primary.btn.disabled,
        .bg-gradient-primary.btn:disabled,
        .bg-gradient-primary.btn:not(:disabled):not(.disabled):active,
        .bg-gradient-primary.btn:not(:disabled):not(.disabled).active,
        .show>.bg-gradient-primary.btn.dropdown-toggle {
            background-image: none !important;
        }

        .bg-gradient-primary.btn:hover {
            background:
                <?php echo $config['secondary_color']; ?> linear-gradient(180deg,
                    <?php echo $config['primary_color']; ?>, #666666) repeat-x !important;
            border-color:
                <?php echo $config['secondary_color']; ?>;
            color: #ececec;
        }

        .bg-gradient-primary.btn:not(:disabled):not(.disabled):active,
        .bg-gradient-primary.btn:not(:disabled):not(.disabled).active,
        .bg-gradient-primary.btn:active,
        .bg-gradient-primary.btn.active {
            background:
                <?php echo $config['secondary_color']; ?> linear-gradient(180deg,
                    <?php echo $config['primary_color']; ?>,
                    <?php echo $config['secondary_color']; ?>) repeat-x !important;
            border-color:
                <?php echo $config['secondary_color']; ?>;
            color: #fff;
        }
    </style>
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo_icon']; ?>" alt="<?php echo $config['site_title']; ?>" height="200">
        </div>
        <nav class="main-header navbar navbar-expand navbar-white navbar-light fixed-top">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item">
                    <a onclick="openModule('meu-perfil');" class="nav-link" style="cursor: pointer; text-align: center;">
                        <i class="fa fa-user"></i>
                        <?php echo $_SESSION['NAME']; ?>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="btn btn-danger text-white " href="<?php echo baseUrl . 'painel/sair' ?>" style="color: red;" title="Sair">
                        <i class="fa fa-sign-out-alt"></i> Sair
                    </a>
                </li>
            </ul>
        </nav>
        <?php
        if (!empty($config['file_menu'])) :
            $imageUrl = baseUrl . 'public/uploads/menu/' . $config['file_menu'];
            $bgStyle = "background-image: url('$imageUrl'); background-size: cover;";
        else :
            $bgStyle = 'background-color:' . $config['primary_color'];
        endif;
        ?>
        <aside class="main-sidebar sidebar-dark-primary elevation-4 text-center" style="<?php echo $bgStyle; ?> !important;">
            <div class="bg-white">
                <a href="<?php echo baseUrl; ?>painel/" class="">
                    <img src="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo']; ?>" alt="logo" style="width: 50%; margin-top: 10px; margin-bottom: 10px;">
                </a>
            </div>
            <div class="sidebar">
                <div class="user-panel mt-3 pb-3 mb-3 d-flex" style="border-bottom: 1px solid white;">
                    <div class="image">
                        <?php if (!empty($_SESSION['PHOTO'])) : ?>
                            <img src="<?php echo baseUrl . 'public/uploads/users/' . $_SESSION['PHOTO']; ?>" class="img-circle elevation-2" alt="<?php echo $_SESSION['NAME']; ?>" style="width: 46px; height: 46px;">
                        <?php else : ?>
                            <img src="<?php echo baseUrl; ?>public/admin/dist/img/avatar5.png" class="img-circle elevation-2" alt="avatar" style="width: 40px;">
                        <?php endif; ?>
                    </div>
                    <div class="info" style="margin-top: -10px;">
                        <a onclick="openModule('meu-perfil');" class="d-block text-white" style="cursor: pointer">
                            <?php echo $_SESSION['NAME']; ?><br>
                            <small><a onclick="openModule('meu-perfil');" class="d-block text-white" style="cursor: pointer">(
                                    <?php echo $_SESSION['ROLE_NAME']; ?>)
                                </a></small>
                        </a>
                    </div>
                </div>
                <nav class="mt-2 text-left">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="true">
                        <?php
                        if (
                            $_SESSION['ROLE_ADM'] == '1'
                            || $canViewHome
                            || $canViewBanners
                            || $canViewTestimonials
                            || $canViewPublications
                            || $canViewAbout
                            || $canViewInternalBanners
                        ) : ?>
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white">
                                    <i class="nav-icon fas fa-globe"></i>
                                    <p>
                                        SITE
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview" style="display: none;">
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewHome) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('home');" class="nav-link text-white " style="cursor: pointer;">
                                                <i class="nav-icon fas fa-home"></i>
                                                <p>
                                                    Home
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewBanners) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('banner');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-images"></i>
                                                <p>
                                                    Banners
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewAbout) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('empresa');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-pen"></i>
                                                <p>
                                                    Empresa
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewServices) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('servicos');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-tools"></i>
                                                <p>
                                                    Serviços
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewPublications) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('blog');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-file"></i>
                                                <p>
                                                    Blog
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewTestimonials) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('depoimentos');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-comment"></i>
                                                <p>
                                                    Depoimentos
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewInternalBanners) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('banners-internos');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-image"></i>
                                                <p>
                                                    Banners Internos
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                        <?php endif; ?>
                        <?php if (
                            $_SESSION['ROLE_ADM'] == '1'
                            || $canViewUsers
                            || $canViewNewsletter
                            || $canViewCategories
                            || $canViewCustomers
                        ) : ?>
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white">
                                    <i class="nav-icon fas fa-users-cog"></i>
                                    <p>
                                        ADMINISTRAÇÃO
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview" style="display: none;">
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewUsers) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('usuarios');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-user-cog"></i>
                                                <p>
                                                    Colaboradores
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewCustomers) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('clientes');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-users"></i>
                                                <p>
                                                    Clientes
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewCategories) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('categorias');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-list"></i>
                                                <p>
                                                    Categorias
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewNewsletter) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('newsletter');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-envelope"></i>
                                                <p>
                                                    Newsletter
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                        <?php endif; ?>
                        <?php if (
                            $_SESSION['ROLE_ADM'] == '1'
                            || $canViewConfigs
                            || $canViewSeo
                            || $canViewSmtp
                            || $canViewLogs
                        ) : ?>
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white">
                                    <i class="nav-icon fas fa-cog"></i>
                                    <p>
                                        SISTEMA
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview" style="display: none;">
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewConfigs) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('configuracoes');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-cogs"></i>
                                                <p>
                                                    Configurações
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1') : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('controle-acesso');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-lock"></i>
                                                <p>
                                                    Controle de Acesso
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewImporter) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('importar');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-upload"></i>
                                                <p>
                                                    Importar Dados
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewLogs) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('logs');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-list"></i>
                                                <p>
                                                    Logs
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewSeo) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('seo');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-globe"></i>
                                                <p>
                                                    SEO
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewSmtp) : ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('smtp');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-envelope-square"></i>
                                                <p>
                                                    SMTP
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                        <?php endif; ?>
                        <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewPolitics) : ?>
                            <li class="nav-item">
                                <a onclick="openModule('politica-privacidade');" class="nav-link text-white" style="cursor: pointer;">
                                    <i class="nav-icon fas fa-eye"></i>
                                    <p>
                                        Política de Privacidade
                                    </p>
                                </a>
                            </li>
                        <?php endif; ?>
                        <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewUseTerms) : ?>
                            <li class="nav-item">
                                <a onclick="openModule('termos-de-uso');" class="nav-link text-white" style="cursor: pointer;">
                                    <i class="nav-icon fas fa-check-circle"></i>
                                    <p>
                                        Termos de Uso
                                    </p>
                                </a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="content-wrapper">
            <div id="sis_content">
                <?php echo $this->content(); ?>
            </div>
            <div class="modal fade" id="modalMid" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalMidLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-primary">
                            <h4 class="modal-title" id="modalMidTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalMidResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalXL">
                <div class="modal-dialog modal-xl">
                    <div class="modal-content">
                        <div class="overlay" id="modalXLLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header bg-primary text-white">
                            <h4 class="modal-title" id="modalXLTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalXLResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalLarge" data-keyboard="false">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="overlay" id="modalLargeLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-primary">
                            <h4 class="modal-title" id="modalLargeTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalLargeResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalDelete" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalDeleteLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-danger">
                            <h4 class="modal-title" id="modalDeleteTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="text-center pt-3">
                            <b>Tem certeza que deseja excluir este registro? <br>Após esta operação, não será possível
                                revertê-la.</b>
                        </div>
                        <div class="modal-body text-center" id="modalDeleteResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalApproval" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalApprovalLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-success">
                            <h4 class="modal-title" id="modalApprovalTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="text-center pt-3">
                            <b>Confirmar ação? <br>Após esta operação, não será possível revertê-la.</b>
                        </div>
                        <div class="modal-body text-center" id="modalApprovalResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalDisapproval" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalDisapprovalLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-danger">
                            <h4 class="modal-title" id="modalDisapprovalTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="text-center pt-3">
                            <b>Confirmar ação? <br>Após esta operação, não será possível revertê-la.</b>
                        </div>
                        <div class="modal-body text-center" id="modalDisapprovalResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalGreenMid" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalGreenMidLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-success">
                            <h4 class="modal-title" id="modalGreenMidTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalGreenMidResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalGreenLarge" data-keyboard="false">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="overlay" id="modalGreenLargeLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-success">
                            <h4 class="modal-title" id="modalGreenLargeTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalGreenLargeResult"></div>
                    </div>
                </div>
            </div>
            <div class="overlay-wrapper" id="baseLoader" style="display: none;">
                <div class="overlay">
                    <i class="fas fa-3x fa-sync-alt fa-spin"></i>
                    <div class="text-bold pt-2 ml-3">Carregando...</div>
                </div>
            </div>
        </div>
        <footer class="main-footer">
            <div class="text-center" style="font-size: 11px">
                <b>Licenciado para</b>
                <?php echo $config['site_title'] ?> &nbsp;
                <b>Versão</b>
                <?php echo $config['version']; ?> <br>
                Sistema desenvolvido por <a href="https://jaconsultoriati.com.br/" target="_blank">JA Consultoria TI</a>
            </div>
        </footer>

    </div>
    <script>
        function openModule(urlParam) {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>painel/" + urlParam,
                async: true
            }).done(function(data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function() {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }
    </script>
    <?php if (!empty($_GET['mod'])) : ?>
        <script>
            openModule('<?php echo $_GET['mod']; ?>');
        </script>
    <?php endif; ?>
</body>

</html>