<?php
$data = $this->view->data;

$isAdmin = $_SESSION['ROLE_ADM'] == '1';
$role = $_SESSION['ROLE'];

$canView = $isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('newsletter'));
$canDelete = $isAdmin || $this->acl($role, $this->resourceCodes('delete'), $this->moduleCodes('newsletter'));
?>
<?php if ($canView): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row mb-2">
                <div class="col-md-11">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-envelope pr-1"></i>
                        Cadastros realizados pelo site
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <a href="<?php echo baseUrl . 'painel'; ?>" class="btn btn-outline-primary w-100"
                                title="Página Inical">
                                <i class="fas fa-home"></i>
                            </a>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover" id="tbl_emails" style="width: 99.9%;">
                                    <thead>
                                        <tr class="text-center" style="height: 30px;">
                                            <th style="font-size: 14px;">Nome</th>
                                            <th style="font-size: 14px;">Email</th>
                                            <th style="display: none;">Cadastrado em</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($data as $entity): ?>
                                            <tr class="text-center" style="height: 30px; cursor: pointer;"
                                                onclick="openDetailsNewsletter('<?php echo $entity['uuid']; ?>');">
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['name']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['email']; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $this->formatDateTime($entity['created_at']); ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">
        $(document).ready(function () {
            let buttonCommon = {
                exportOptions: {
                    format: {
                        body: function (data) {
                            return data;
                        }
                    }
                }
            };

            $('#tbl_emails').DataTable({
                "sDom": 'flBtip',
                searching: true,
                buttons: [
                    $.extend(true, {}, buttonCommon, {
                        extend: 'excel',
                        title: 'Lista de Emails',
                        exportOptions: { columns: [0, 1, 2] }
                    })
                ],
                order: [[0, "asc"]],
                responsive: true,
                info: true,
                processing: true,
                scrollCollapse: true,
                paging: true,
                "pageLength": 25,
                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ &nbsp;",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Filtrar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });

        function openDetailsNewsletter(uuid) {
            $("#modalLargeResult").empty();
            $("#modalLargeTitle").html('<i class="fa fa-th-list"></i> Dados do cadastro');
            $("#modalLargeLoader").show();
            $("#modalLarge").modal('show');

            $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>painel/newsletter/detalhes",
                data: { uuid: uuid },
                async: true
            }).done(function (data) {
                $("#modalLargeResult").html(data);
                $("#modalLargeLoader").hide();
            }).fail(function () {
                showInternalErrorAlert();
                $("#modalLargeLoader").hide();
            });
        }
    </script>
    <?php if ($canDelete): ?>
        <script>
            function deleteNewsletter(uuid) {
                $("#modalXL").modal('hide');
                $("#modalDeleteTitle").html('<i class="fa fa-trash pr-2"></i> Remover Cadastro');
                $("#modalDeleteLoader").hide();
                $("#modalDelete").modal('show');
                $("#modalDeleteResult").html('<button type="button" class="btn btn-danger" title="Confirmar remoção" onclick="runDelete(\'' + uuid + '\');"><i class="fa fa-trash"></i> CONFIRMAR E EXCLUIR</button>');
            }

            function runDelete(uuid) {
                if (uuid !== null) {
                    $("#modalDeleteLoader").show();

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>painel/newsletter/excluir",
                        data: { uuid: uuid },
                        dataType: 'json',
                        async: true
                    }).done(function (data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#modalDelete").modal('hide');
                        $("#modalLarge").modal('hide');
                        openModule('newsletter');
                    }).fail(function () {
                        showInternalErrorAlert();
                        $("#modalDeleteLoader").hide();
                    });
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>