<link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/plugins/jquery-toast-plugin/dist/jquery.toast.min.css">
<div class="inner-banner" style="background-image: url('<?php echo $this->getInternalBanner('file_customers'); ?>'); background-size: cover;">
  <section class="w3l-breadcrumb">
    <div class="container">
      <ul class="breadcrumbs-custom-path">
      <li class="active" style="font-size: 50px; text-shadow: black 0.1em 0.1em 0.2em;">Login / Cadastro</li>
      </ul>
    </div>
  </section>
</div>
<section class="w3l-contact-1 py-5" id="contact">
    <div class="contacts-9 py-lg-5 py-md-4">
        <div class="container">
            <div class="d-grid contact-view mb-5 pb-lg-5">
                <div class="map-content-9">
                    <div class="contactct-fm map-content-9 pl-lg-4">
                        <div class="contactct-fm-text text-left">
                            <div class="header-title mb-md-5 mt-4">
                                <span class="sub-title">Alterar Senha</span>
                                <h3 class="hny-title text-left">Informa sua nova senha</h3>
                            </div>
                        </div>
                        <form action="<?php echo baseUrl; ?>area-clientes/alterar-senha" method="post" onsubmit="hashPass(this);">
                            <div class="">
                                <input type="password" class="form-control" name="password" id="password"
                                    placeholder="Senha" required="" minlength="8" maxlength="100">
                            </div>
                            <div class=" mt-3">
                                <input type="password" class="form-control" name="confirmation" id="confirmation"
                                    placeholder="Confirme a Senha" required="" minlength="8" maxlength="100">
                            </div>
                            <div class="text-right">
                                <input type="hidden" name="info" value="<?php echo $this->view->code; ?>">
                                <button type="submit" class="btn btn-primary btn-style mt-4 btnAction">Confirmar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="<?php echo baseUrl; ?>public/admin/plugins/jquery/jquery.min.js"></script>
<script src="<?php echo baseUrl; ?>public/admin/plugins/jquery-toast-plugin/dist/jquery.toast.min.js"></script>
<script src="<?php echo baseUrl; ?>public/admin/js/alerts.js"></script>
<script src="<?php echo baseUrl; ?>public/js/md5.min.js"></script>
<script>
    function hashPass(form) {
        if (form.password.value !== '') {
            form.password.value = md5(form.password.value);
        }

        if (form.confirmation.value !== '') {
            form.confirmation.value = md5(form.confirmation.value);
        }
    }
</script>
<?php if (!empty($this->view->errorPasswords)): ?>
    <script>
        showAlert('error', 'Ops!', '<?php echo $this->view->errorPasswords; ?>', 'top-center');
    </script>
<?php endif; ?>