<link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/plugins/jquery-toast-plugin/dist/jquery.toast.min.css">
<div class="inner-banner" style="background-image: url('<?php echo $this->getInternalBanner('file_customers'); ?>'); background-size: cover;">
  <section class="w3l-breadcrumb">
    <div class="container">
      <ul class="breadcrumbs-custom-path">
      <li class="active" style="font-size: 50px; text-shadow: black 0.1em 0.1em 0.2em;">Login / Cadastro</li>
      </ul>
    </div>
  </section>
</div>
<section class="w3l-contact-1 py-5" id="contact">
    <div class="contacts-9 py-lg-5 py-md-4">
        <div class="container">
            <div class="d-grid contact-view mb-5 pb-lg-5">
                <div class="cont-details">
                    <div class="contactct-fm map-content-9 pl-lg-4">
                        <div class="contactct-fm-text text-left">
                            <div class="header-title mb-md-5 mt-4">
                                <span class="sub-title">Validar Token</span>
                                <h3 class="hny-title text-left">Token para Recuperação</h3>
                            </div>
                        </div>
                        <form action="<?php echo baseUrl; ?>area-clientes/token-senha" method="post" onsubmit="hashPass(this);">
                            <div class="twice">
                                <input type="password" class="form-control" name="token" id="token"
                                    placeholder="Token" required="">
                            </div>
                            <div class="text-left">
                                <button type="submit" class="btn btn-primary btn-style mt-4 btnAction">Confirmar</button>
                              <a href="<?php echo baseUrl . 'area-clientes' ?>" class="pull-right pt-4">Voltar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="<?php echo baseUrl; ?>public/admin/plugins/jquery/jquery.min.js"></script>
<script src="<?php echo baseUrl; ?>public/admin/plugins/jquery-toast-plugin/dist/jquery.toast.min.js"></script>
<script src="<?php echo baseUrl; ?>public/admin/js/alerts.js"></script>
<script src="<?php echo baseUrl; ?>public/js/md5.min.js"></script>
<script>
    function hashPass(form) {
        if (form.token.value !== '') {
            form.token.value = md5(form.token.value);
        }
    }
</script>
<?php if (!empty($_GET['msg']) && $_GET['msg'] == 'token-invalido'): ?>
    <script>
        showAlert('error', 'Ops!', 'Token inválido, tente novamente.', 'top-center');
    </script>
<?php endif; ?>