<?php 
$config = $this->getSiteConfig();
$entity = $this->view->entity; 
?>
<link rel="stylesheet" href="<?php echo baseUrl; ?>public/admin/plugins/jquery-toast-plugin/dist/jquery.toast.min.css">
<div class="inner-banner" style="background-image: url('<?php echo $this->getInternalBanner('file_customers'); ?>'); background-size: cover;">
  <section class="w3l-breadcrumb">
    <div class="container">
      <ul class="breadcrumbs-custom-path">
      <li class="active" style="font-size: 50px; text-shadow: black 0.1em 0.1em 0.2em;">Meu Perfil</li>
      </ul>
    </div>
  </section>
</div>
<section class="w3l-contact-1 py-5" id="contact">
    <div class="contacts-9 py-lg-5 py-md-4">
        <div class="container">
            <div class=" contact-view mb-5 pb-lg-5">
                <div class="cont-details">
                    <div class="contactct-fm map-content-9 pl-lg-4">
                        <form action="<?php echo baseUrl; ?>area-clientes/meus-dados" method="post" onsubmit="hashPass(this);">
                            <div class="row">
                                <div class="header-title mb-3">
                                    <span class="sub-title">Dados Pessoais</span>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="name">Nome</label>
                                        <input type="text" class="form-control" name="name" id="name" required maxlength="200"
                                            value="<?php echo $entity['name']; ?>">
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="phone">Telefone</label>
                                        <input type="text" class="form-control" name="phone" id="phone"
                                            value="<?php echo $entity['phone']; ?>">
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="cellphone">Celular</label>
                                        <input type="text" class="form-control" name="cellphone" id="cellphone"
                                            value="<?php echo $entity['cellphone']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-12 mb-5 mt-5" style="border-radius: 5px;">
                                    <span class="sub-title">Dados de Acesso</span>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <input type="email" class="form-control" name="email" id="email" required maxlength="100"
                                            value="<?php echo $entity['email']; ?>">
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="password">Senha</label>
                                        <input type="password" class="form-control" name="password" id="password" minlength="8" maxlength="100"
                                            placeholder="Nova Senha">
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="confirmation">Confirmar Senha</label>
                                        <input type="password" class="form-control" name="confirmation" id="confirmation" minlength="8" maxlength="100"
                                            placeholder="Confirmar Senha">
                                    </div>
                                </div>
                                <div class="col-md-12 mb-5 mt-5" style="border-radius: 5px;">
                                    <span class="sub-title">Localização</span>
                                </div>
                                <div class="col-12 col-md-4">
                                    <div class="form-group">
                                        <label for="postal_code">CEP</label>
                                        <input type="text" class="form-control" name="postal_code" id="postal_code" 
                                            value="<?php echo $entity['postal_code']; ?>">
                                    </div>
                                </div>
                                <div class="col-12 col-md-8">
                                    <div class="form-group">
                                        <label for="address">Endereço</label>
                                        <input type="text" class="form-control" name="address" id="address"  maxlength="100"
                                            value="<?php echo $entity['address']; ?>" readonly>
                                    </div>
                                </div>
                                <div class="col-12 col-md-3">
                                    <div class="form-group">
                                        <label for="number">Número</label>
                                        <input type="text" class="form-control" name="number" id="number"  maxlength="50"
                                            value="<?php echo $entity['number']; ?>">
                                    </div>
                                </div>
                                <div class="col-12 col-md-4">
                                    <div class="form-group">
                                        <label for="complement">Complemento</label>
                                        <input type="text" class="form-control" name="complement" id="complement"  maxlength="50"
                                            value="<?php echo $entity['complement']; ?>">
                                    </div>
                                </div>
                                <div class="col-12 col-md-5">
                                    <div class="form-group">
                                        <label for="neighborhood">Bairro</label>
                                        <input type="text" class="form-control" name="neighborhood" id="neighborhood"  maxlength="100"
                                            value="<?php echo $entity['neighborhood']; ?>" readonly>
                                    </div>
                                </div>
                                <div class="col-12 col-md-8">
                                    <div class="form-group">
                                        <label for="city">Cidade</label>
                                        <input type="text" class="form-control" name="city" id="city"  maxlength="100" readonly
                                            value="<?php echo $entity['city']; ?>">
                                    </div>
                                </div>
                                <div class="col-12 mb-4 col-md-4">
                                    <div class="form-group">
                                        <label for="state">UF</label>
                                        <input type="text" class="form-control" name="state" id="state"  maxlength="2" readonly
                                            value="<?php echo $entity['state']; ?>">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="row">
                                        <div class="col-md-8 mt-2 mb-2">
                                            <button type="submit" class="btn btn-success w-100" id="btnSubmit"
                                                title="Salvar Imóvel">
                                                <i class="fa fa-save pr-1"></i> Salvar
                                            </button>
                                        </div>
                                        <div class="col-md-4 mt-2 mb-2">
                                            <a href="<?php echo baseUrl; ?>area-clientes" 
                                                class="btn btn-outline-primary w-100">
                                                <i class="fas fa-arrow-left pr-1"></i> Voltar 
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="<?php echo baseUrl; ?>public/admin/plugins/jquery/jquery.min.js"></script>
<script src="<?php echo baseUrl; ?>public/admin/plugins/jquery-toast-plugin/dist/jquery.toast.min.js"></script>
<script src="<?php echo baseUrl; ?>public/admin/js/alerts.js"></script>
<script src="<?php echo baseUrl; ?>public/js/documents_validators.js"></script>
<script src="<?php echo baseUrl; ?>public/js/md5.min.js"></script>
<script>
    function hashPass(form) {
        if (form.password.value !== '') {
            form.password.value = md5(form.password.value);
        }

        if (form.confirmation.value !== '') {
            form.confirmation.value = md5(form.confirmation.value);
        }
    }

    function cleanPostalCodeForm() {
        // Limpa valores do formulário de cep.
        $("#address").val("");
        $("#neighborhood").val("");
        $("#city").val("");
        $("#state").val("");
        
        $("#postal_code").val("").focus();
        //$("#ibge").val("");
    }

    $(document).ready(function(){
        $("#document_1").mask("999.999.999-99");
        $("#document_2").mask("99.999.999/9999-99");
        $("#phone").mask("(99)9999-9999");
        $("#cellphone").mask("(99)99999-9999");
        $("#postal_code").mask("99999-999");
    
        //Quando o campo cep perde o foco.
        $("#postal_code").blur(function() {
            //Nova variável "cep" somente com dígitos.
            let postal_code = $(this).val().replace(/\D/g, '');
            //Verifica se campo cep possui valor informado.
            if (postal_code !== "") {
                //Expressão regular para validar o CEP.
                let validatePostalCode = /^[0-9]{8}$/;
                //Valida o formato do CEP.
                if(validatePostalCode.test(postal_code)) {
                    //Preenche os campos com "..." enquanto consulta webservice.
                    $("#address").val("...");
                    $("#neighborhood").val("...");
                    $("#city").val("...");
                    $("#state").val("...");
                    //$("#ibge").val("...");
                    //Consulta o webservice viacep.com.br/
                    $.getJSON("https://viacep.com.br/ws/"+ postal_code +"/json/?callback=?", function(data) {
                        if (!("erro" in data)) {
                            //Atualiza os campos com os valores da consulta.
                            $("#address").val(data.logradouro);
                            $("#neighborhood").val(data.bairro);
                            $("#city").val(data.localidade);
                            $("#state").val(data.uf);
                            //$("#ibge").val(dados.ibge);
                        } else {
                            //CEP pesquisado não foi encontrado.
                            cleanPostalCodeForm();
                            alert("CEP não encontrado.");
                        }
                    });
                } else {
                    //cep é inválido.
                    cleanPostalCodeForm();
                    alert("Formato de CEP inválido.");
                }
            } else {
                //cep sem valor, limpa formulário.
                cleanPostalCodeForm();
            }
        });
    });
</script>
<?php if (!empty($_GET['msg']) && $_GET['msg'] == 'erro'): ?>
    <script>
        showAlert('error', 'Ops!', 'Erro ao atualizar perfil, tente novamente.', 'top-center');
    </script>
<?php endif; ?>
<?php if (!empty($_GET['msg']) && $_GET['msg'] == 'salvo'): ?>
    <script>
        showAlert('success', 'Sucesso!', 'Seu perfil foi atualizado.', 'top-center');
    </script>
<?php endif; ?>
<?php if (!empty($_GET['msg']) && $_GET['msg'] == 'senhas-incorretas'): ?>
    <script>
        showAlert('error', 'Ops!', 'Senhas incorretas, tente novamente.', 'top-center');
    </script>
<?php endif; ?>
<?php if (!empty($_GET['msg']) && $_GET['msg'] == 'cpf-ja-cadastrado'): ?>
    <script>
        showAlert('error', 'Ops!', 'Este CPF está em uso, tente novamente.', 'top-center');
    </script>
<?php endif; ?>
<?php if (!empty($_GET['msg']) && $_GET['msg'] == 'cnpj-ja-cadastrado'): ?>
    <script>
        showAlert('error', 'Ops!', 'Este CNPJ está em uso, tente novamente.', 'top-center');
    </script>
<?php endif; ?>
<?php if (!empty($_GET['msg']) && $_GET['msg'] == 'email-ja-cadastrado'): ?>
    <script>
        showAlert('error', 'Ops!', 'Este EMAIL está em uso, tente novamente.', 'top-center');
    </script>
<?php endif; ?>
<?php if (!empty($_GET['msg']) && $_GET['msg'] == 'celular-ja-cadastrado'): ?>
    <script>
        showAlert('error', 'Ops!', 'Este CELULAR está em uso, tente novamente.', 'top-center');
    </script>
<?php endif; ?>
<?php if (!empty($_GET['msg']) && $_GET['msg'] == 'nome-ja-cadastrado'): ?>
    <script>
        showAlert('error', 'Ops!', 'Este NOME está em uso, tente novamente.', 'top-center');
    </script>
<?php endif; ?>