<?php
$entity = $this->view->entity;
$config = $this->getSiteConfig();
?>
<div class="inner-banner" style="background-image: url('<?php echo $this->getInternalBanner('file_services'); ?>'); background-size: cover;">
    <section class="w3l-breadcrumb">
        <div class="container">
            <ul class="breadcrumbs-custom-path mt-3">
                <li>
                    <h1 style=" color: white; font-size: 50px;">Detalhes do Serviço</h1>
                </li>
            </ul>
        </div>
    </section>
</div>
<section class="w3l-blogpost-content w3l-courses py-5">
    <div class="container pt-md-3">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12 text-center mb-3">
                                <h2><?php echo $entity['title']; ?></h2>
                                <hr>
                            </div>
                            <?php if (!empty($this->view->files)): ?>
                                    <div class="col-md-6 pb-3">
                                        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                                            <div class="carousel-inner" style="box-shadow: 0 0 0.5em <?php echo $config['secondary_color'] ?>;">
                                                <?php $i = 0; ?>
                                                <?php foreach ($this->view->files as $file): ?>
                                                        <?php $i++; ?>
                                                        <div class="carousel-item <?php echo ($i == 1) ? 'active' : ''; ?>">
                                                            <img src="<?php echo baseUrl . 'public/uploads/services/' . $entity['uuid'] . '/' . $file['file']; ?>"
                                                                 class="d-block w-100" alt="<?php echo $entity['title']; ?>" style="width: 100%;">
                                                        </div>
                                                <?php endforeach; ?>
                                            </div>
                                            <?php if (count($this->view->files) > 1): ?>
                                                    <button class="carousel-control-prev" type="button" data-target="#carouselExampleControls" data-slide="prev"
                                                            style="background: transparent; border: 0;">
                                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                                        <span class="sr-only">Previous</span>
                                                    </button>
                                                    <button class="carousel-control-next" type="button" data-target="#carouselExampleControls" data-slide="next"
                                                            style="background: transparent; border: 0;">
                                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                                        <span class="sr-only">Next</span>
                                                    </button>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <div class="col-md-6 pb-3">
                                        <p><?php echo $entity['description']; ?></p>
                                    </div>
                            <?php else: ?>
                                    <div class="col-md-12">
                                        <p><?php echo $entity['description']; ?></p>
                                    </div>
                            <?php endif; ?>
                    </div>
                    </div>
                </div>
            </div>
            <div class="col-12 text-center">
                <div class="main-social-footer-29 text-center mt-5">
                    <span class="pr-2"><b>Compartilhe este Serviço:</b></span>
                    <a id="whatsapp-share-btt" rel="nofollow" target="_blank" class="whatsapp-share-button">
                        <span class="fa fa-whatsapp"></span>
                    </a>
                    <a id="facebook-share-btt" rel="nofollow" target="_blank" class="facebook-share-button">
                        <span class="fa fa-facebook">
                    </a>
                    <a id="twitter-share-btt" rel="nofollow" target="_blank" class="twitter-share-button">
                        <span class="fa fa-twitter"></span>
                    </a>
                </div>
            </div>
            <div class="col-md-12 mt-4 text-center">
                <div class="pt-4">
                    <a href="<?php echo baseUrl . 'servicos'; ?>" class="btn btn-primary btn-xs mt-3"><span class="fa fa-arrow-left pr-2"></span>Voltar</a>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="<?php echo baseUrl . 'public/js/jquery.min.js' ?>"></script>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
        let conteudo = encodeURIComponent("<?php echo $config['site_title']; ?> - <?php echo $entity['title']; ?> " + window.location.href);
        document.getElementById("whatsapp-share-btt").href = "https://api.whatsapp.com/send?text=" + conteudo;
    }, false);
    document.addEventListener("DOMContentLoaded", function() {
        document.getElementById("facebook-share-btt").href = "https://www.facebook.com/sharer/sharer.php?u=" + encodeURIComponent(window.location.href);
    }, false);
    document.addEventListener("DOMContentLoaded", function() {
        let url = encodeURIComponent(window.location.href);
        document.getElementById("twitter-share-btt").href = "https://twitter.com/intent/tweet?url="+url+"&text="+"<?php echo $config['site_title']; ?> - <?php echo $entity['title']; ?> " ;
    }, false);
</script>
